---

- name: Remove default cron.daily files.
  when: aspects_logwatch_enabled
  file:
    state: "absent"
    path: "{{ item }}"
  loop:
    - "/etc/cron.daily/00logwatch"
    - "/etc/cron.daily/0logwatch"
  tags:
    - aspects_logwatch

- name: Add /etc/logwatch/conf/services files.
  when:
    - aspects_logwatch_enabled
    - aspects_logwatch_conf_services is defined
  copy:
    src: "{{ inventory_dir }}/{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ aspects_logwatch_conf_services | default({}) | dictsort }}"
  tags:
    - aspects_logwatch
    - aspects_logwatch_conf_services
